name: PR

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install and run Luacheck
      run: |
        sudo apt-get install luarocks
        luarocks install --local luacheck
        /home/runner/.luarocks/bin/luacheck . --no-color -q

    - name: Install and run busted
      run: |
        sudo apt-get install luarocks
        luarocks install --local busted
        curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash -s -- -d -z
        cd .release/LibClassicTalentQuery
        /home/runner/.luarocks/bin/busted --shuffle --output=plainTerminal .

    - name: Create Package
      run: curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash -s -- -d -z
      env:
        CF_API_KEY: ${{ secrets.CF_API_KEY }}
        GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
        WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}

    - uses: actions/upload-artifact@master
      with:
        name: LibClassicTalentQuery-PR
        path: .release/
